### ISSUE TITLE
OSX Sonoma - Decredition does not work

### ISSUE THREAD

**Issue by mantaskalausis** [decred/decred-binaries#155]
When launching the app in OSX Sonoma (Version 14.5 (23F79)). The OS is freshly installed and updated. There are no other changes to the OS. It is an unmanaged vanilla install on original Mac hardware (Macbook Pro 16in 2019) - Intel CPU - 2,6 GHz 6-Core Intel Core i7

<img width="548" alt="Screenshot 2024-05-22 at 13 32 11" src="https://github.com/decred/decred-binaries/assets/6515881/7e906306-e783-4451-9201-c73810f816d8">

Uncaught Exception:
Error: node-loader:
Error: dlopen(/var/folders/44/51yf132j6d91rb2sr_528q6r0000gn/T/.com.Electron.Decrediton.KyGvtr, 0x0001): tried: '/var/folders/44/51yf132j6d91rb2sr_528q6r0000gn/T/.com.Electron.Decrediton.KyGvtr' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/44/51yf132j6d91rb2sr_528q6r0000gn/T/.com.Electron.Decrediton.KyGvtr' (no such file), '/var/folders/44/51yf132j6d91rb2sr_528q6r0000gn/T/.com.Electron.Decrediton.KyGvtr' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/private/var/folders/44/51yf132j6d91rb2sr_528q6r0000gn/T/.com.Electron.Decrediton.KyGvtr' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/44/51yf132j6d91rb2sr_528q6r0000gn/T/.com.Electron.Decrediton.KyGvtr' (no such file), '/private/var/folders/44/51yf132j6d91rb2sr_528q6r0000gn/T/.com.Electron.Decrediton.KyGvtr' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))
at 17597 (/Applications/Decrediton.app/Contents/Resources/app.asar/main.js:8:313282)
at __webpack_require__ (/Applications/Decrediton.app/Contents/Resources/app.asar/main.js:8:1617193)
at 24902 (/Applications/Decrediton.app/Contents/Resources/app.asar/main.js:8:373640)
at __webpack_require__ (/Applications/Decrediton.app/Contents/Resources/app.asar/main.js:8:1617193)
at Y (/Applications/Decrediton.app/Contents/Resources/app.asar/main.js:2:153198)
at Q (/Applications/Decrediton.app/Contents/Resources/app.asar/main.js:2:153740)
at 81015 (/Applications/Decrediton.app/Contents/Resources/app.asar/main.js:2:114363)
at __webpack_require__ (/Applications/Decrediton.app/Contents/Resources/app.asar/main.js:8:1617193)
at /Applications/Decrediton.app/Contents/Resources/app.asar/main.js:8:1617456
at Object.<anonymous> (/Applications/Decrediton.app/Contents/Resources/app.asar/main.js:8:1617484)

**Comment by alexlyp** [comment]
Try it again.  I re rolled the amd64 version
